### ISSUE TITLE
Compatibility with react-bem-helper

### ISSUE THREAD

**Issue by pavyarov** [redneckz/react-devirt#1]
There are some issues with devirt if we using react-bem-helper.

Example: 
```
import { BEM } from '@redneckz/react-bem-helper';
import { devirt } from '@redneckz/react-devirt';

import styles from './foo.module.css';

devirt();

const foo = BEM(styles);

const Foo = foo(({ className }) => {
    return <div className={className} />;
});
```

This code will produce: 
![image](https://user-images.githubusercontent.com/25486791/66656919-9188b700-ec47-11e9-9f97-6e6db2de8980.png)

![image](https://user-images.githubusercontent.com/25486791/66656980-b67d2a00-ec47-11e9-8fc2-f23df34054da.png)

**Comment by redneckz** [comment]
Fixed in #v0.0.5
